name: build-and-test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.14
          - 1
          - master
        db:
          - mariadb:10.1
          - mariadb:10.2
          - mariadb:latest
          - mysql:5.6
          - mysql:5.7
          - mysql:latest
          - spanner
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Run tests
        run: |
          make \
            GO_VERSION=${{ matrix.go_version }} \
            TARGET_DB=${{ matrix.db }} \
            test-on-docker
